fixtures:
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    yumrepo_core: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
  symlinks:
    yarn: "#{source_dir}"
