---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
script: "bundle exec rake test"
rvm:
  - 2.2
  - 2.3
  - 2.4
env:
  - PUPPET_VERSION='~> 4.0'
  - PUPPET_VERSION='~> 5.0'
notifications:
  email: false
