---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
script: "bundle exec rake test"
rvm:
  - 2.4
  - 2.5
  - 2.6
env:
  - PUPPET_VERSION='~> 5.0'
  - PUPPET_VERSION='~> 6.0'
notifications:
  email: false
