---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
script: "bundle exec rake test"
rvm:
  - 2.2
  - 2.3
  - 2.4
env:
  - PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.2.0"
  - PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - PUPPET_VERSION='~> 4.0'
  - PUPPET_VERSION='~> 5.0'
notifications:
  email: false
